title:            乐潇游
description:      快乐，潇洒，自游儿~
url:              http://ngoctran.me/zebra/
signoff:          Ngoc Tran

links:
  - name:         首页
    url:          /
  - name:         关于我
    url:          /sample-page

permalink:        pretty
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
